name: StarkLotto Contracts CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "packages/snfoundry/contracts/**"
      - ".github/workflows/**"

  push:
    branches:
      - dev
    paths:
      - "packages/snfoundry/contracts/**"
      - ".github/workflows/**"

jobs:
  build-and-test-contracts:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Scarab (compatible con Cairo 2.11.4)
      - name: Setup Scarab
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.4"

      # 3. Setup Snfoundry (Starknet Foundry)
      - name: Setup Snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: ./.tool-versions

      # 4. Install dependencies and build contracts
      - name: Fetch dependencies and build
        run: |
          scarb fetch
          scarb build
        working-directory: ./packages/snfoundry/contracts

      # 5. List all tests detected
      - name: List tests
        run: snforge test -- --list
        working-directory: ./packages/snfoundry/contracts

      # 6. Run tests in verbose mode and print logs
      - name: Run snfoundry tests (verbose + logs)
        run: snforge test -- -v --print-logs
        working-directory: ./packages/snfoundry/contracts
        env:
          RUST_BACKTRACE: 1
          SNFORGE_FORMAT: pretty
