name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Scarb
        uses: actions-rs/install@v0.1
        with:
          crate: scarb
          use-tool-cache: true

      - name: Install Starknet Foundry
        uses: actions-rs/install@v0.1
        with:
          crate: snforge
          use-tool-cache: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn format:check

      - name: Lint frontend
        run: yarn next:lint
        working-directory: packages/nextjs

      - name: Check TypeScript types
        run: yarn next:check-types
        working-directory: packages/nextjs

      - name: Run frontend tests
        run: yarn test:nextjs
        working-directory: packages/nextjs

      - name: Compile contracts
        run: yarn compile
        working-directory: packages/snfoundry

      - name: Run contract tests
        run: yarn test
        working-directory: packages/snfoundry

      - name: Build frontend
        run: yarn build
        working-directory: packages/nextjs
