name: Snfoundry Contracts CI

on:
  push:
    branches: [dev]
    paths:
      - "packages/snfoundry/contracts/**"
  pull_request:
    branches: [dev]
    paths:
      - "packages/snfoundry/contracts/**"
      - ".github/workflows/**"

jobs:
  build-and-test-contracts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ScarB
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.9.4"

      - name: Setup snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: ./.tool-versions

      - name: Run snforge tests (verbose + logs)
        env:
          RUST_BACKTRACE: 1
          SNFORGE_FORMAT: pretty
        run: snforge test -- -v --print-logs
        working-directory: ./packages/snfoundry/contracts
